In [56]:
import numpy as np
import pandas as pd

In [57]:
PATH = '/data/'
ext = '.csv'
#full data from 1991
start1 = 2018 #1968
end1 = 2018
ft1 = 'atp_matches_'

In [58]:
def readfiles(ft,st,en):
    l = []
    for i in range(st,en+1):
        p = ft + str(i)+ ext
        #print(p)
        df = pd.read_csv(p)
        l.append(df)
        #print(df.head(2))
    return l

In [59]:
f1 = readfiles(ft1,start1,end1)

In [60]:
all_matches = pd.concat(f1)
all_matches.describe()

,draw_size,tourney_date,match_num,winner_id,winner_seed,winner_ht,winner_age,winner_rank,winner_rank_points,loser_id,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
count,2494.000000,2.494000e+03,2494.000000,2494.000000,948.000000,1660.000000,2494.000000,2487.000000,2487.000000,2494.000000,...,2473.000000,2473.000000,2473.000000,2473.000000,2473.000000,2473.000000,2473.000000,2473.000000,2473.000000,2473.000000
mean,61.589415,2.018048e+07,231.905774,109729.885726,8.126582,186.912048,27.628326,88.418979,1603.599920,111484.771451,...,5.129802,5.594015,3.572988,84.093409,50.841892,34.318237,15.439143,11.650222,4.863728,8.677719
std,44.142876,2.485647e+02,91.467684,14857.070038,7.624144,7.986847,4.630301,163.833733,1793.900975,18561.077638,...,3.992374,5.435946,2.606244,30.258697,19.844166,15.126202,7.247338,5.223811,3.332023,4.233006
min,4.000000,2.018010e+07,1.000000,100644.000000,1.000000,163.000000,14.926762,1.000000,1.000000,100644.000000,...,0.000000,0.000000,0.000000,11.000000,6.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,32.000000,2.018022e+07,200.000000,104898.000000,3.000000,183.000000,23.986995,21.000000,638.000000,104925.000000,...,2.000000,2.000000,2.000000,61.000000,36.000000,24.000000,10.000000,9.000000,2.000000,6.000000
50%,32.000000,2.018043e+07,275.000000,105526.000000,6.000000,185.000000,27.994524,51.000000,981.000000,105583.000000,...,4.000000,4.000000,3.000000,79.000000,48.000000,32.000000,14.000000,11.000000,4.000000,8.000000
75%,128.000000,2.018072e+07,289.000000,106298.000000,10.000000,190.000000,31.102669,91.000000,1757.000000,106378.000000,...,7.000000,8.000000,5.000000,101.000000,62.000000,43.000000,20.000000,15.000000,7.000000,11.000000
max,128.000000,2.018092e+07,701.000000,208029.000000,32.000000,208.000000,39.378508,1821.000000,10600.000000,207973.000000,...,25.000000,61.000000,18.000000,291.000000,218.000000,171.000000,50.000000,50.000000,22.000000,28.000000

In [61]:
all_matches.info()
#all_matches=all_matches.dropna(axis=0,how='any')
all_matches = all_matches[np.isfinite(all_matches['loser_rank'])]
all_matches = all_matches[np.isfinite(all_matches['winner_rank'])]

#print("shape is ",all_matches.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2494 entries, 0 to 2493
Data columns (total 49 columns):
tourney_id            2494 non-null object
tourney_name          2494 non-null object
surface               2494 non-null object
draw_size             2494 non-null int64
tourney_level         2494 non-null object
tourney_date          2494 non-null int64
match_num             2494 non-null int64
winner_id             2494 non-null int64
winner_seed           948 non-null float64
winner_entry          323 non-null object
winner_name           2494 non-null object
winner_hand           2490 non-null object
winner_ht             1660 non-null float64
winner_ioc            2494 non-null object
winner_age            2494 non-null float64
winner_rank           2487 non-null float64
winner_rank_points    2487 non-null float64
loser_id              2494 non-null int64
loser_seed            585 non-null float64
loser_entry           494 non-null object
loser_name            2494 non-null object
loser_hand            2483 non-null object
loser_ht              1479 non-null float64
loser_ioc             2494 non-null object
loser_age             2491 non-null float64
loser_rank            2463 non-null float64
loser_rank_points     2463 non-null float64
score                 2494 non-null object
best_of               2494 non-null int64
round                 2494 non-null object
minutes               2482 non-null float64
w_ace                 2473 non-null float64
w_df                  2473 non-null float64
w_svpt                2473 non-null float64
w_1stIn               2473 non-null float64
w_1stWon              2473 non-null float64
w_2ndWon              2473 non-null float64
w_SvGms               2473 non-null float64
w_bpSaved             2473 non-null float64
w_bpFaced             2473 non-null float64
l_ace                 2473 non-null float64
l_df                  2473 non-null float64
l_svpt                2473 non-null float64
l_1stIn               2473 non-null float64
l_1stWon              2473 non-null float64
l_2ndWon              2473 non-null float64
l_SvGms               2473 non-null float64
l_bpSaved             2473 non-null float64
l_bpFaced             2473 non-null float64
dtypes: float64(29), int64(6), object(14)
memory usage: 954.8+ KB

In [62]:
to_drop = ['tourney_id','tourney_date','winner_id','winner_name','loser_id','loser_name','score']
cat_cols = ['tourney_name','surface','draw_size','tourney_level','winner_entry','winner_hand','winner_ioc',
            'loser_entry','loser_hand','loser_ioc','best_of','round']
num_cols = ['match_num','winner_seed','winner_ht','winner_age','winner_rank_points',
            'loser_seed','loser_ht','loser_age','loser_rank_points','minutes',
            'w_ace','w_df','w_svpt','w_1stIn','w_1stWon','w_2ndWon','w_SvGms','w_bpSaved',
             'w_bpFaced','l_ace','l_df','l_svpt','l_1stIn','l_1stWon','l_2ndWon','l_SvGms','l_bpSaved','l_bpFaced']
num_cols1 = ['match_num','winner_seed','winner_ht','winner_age',
            'loser_seed','loser_ht','loser_age','minutes',
            'w_ace','w_df','w_svpt','w_1stIn','w_1stWon','w_2ndWon','w_SvGms','w_bpSaved',
             'w_bpFaced','l_ace','l_df','l_svpt','l_1stIn','l_1stWon','l_2ndWon','l_SvGms','l_bpSaved','l_bpFaced']
all_matches = all_matches.drop(to_drop, axis=1)

In [63]:
#all_matches = all_matches.fillna(all_matches.mean())
for i in cat_cols:
    all_matches[i] = all_matches[i].replace(np.NaN, all_matches[i].mode())

for i in num_cols:
    all_matches[i] = all_matches[i].replace(np.NaN,all_matches[i].mean())
    
all_matches = pd.get_dummies(all_matches, columns=cat_cols)



def normalize(dff,col_name_list):
    result = dff.copy()
    for feature_name in col_name_list:
        max_value = dff[feature_name].max()
        min_value = dff[feature_name].min()
        result[feature_name] = (dff[feature_name] - min_value) / (max_value - min_value)
    return result


all_matches = normalize(all_matches,num_cols)

In [64]:
loserrank = pd.DataFrame(all_matches['loser_rank'])
winnerrank = pd.DataFrame(all_matches['winner_rank'])


all_matches = all_matches.drop(['winner_rank','loser_rank'], axis=1)

loserrankDF=all_matches.copy()
winnerrankDF=all_matches.copy()

In [65]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2 
#winnerrankDF=SelectKBest(chi2, k=10).fit_transform(winnerrankDF, winnerrank)
#loserrankDF=SelectKBest(chi2, k=10).fit_transform(loserrankDF, loserrank)

all_matches.to_csv('winnerrank.csv', encoding='utf-8', index=False)
all_matches.to_csv('loserrank.csv', encoding='utf-8', index=False)
winnerrankDF=pd.read_csv('winnerrank.csv')
loserrankDF=pd.read_csv('loserrank.csv')

In [66]:
from sklearn.model_selection import train_test_split
y1=winnerrank
y2=loserrank
x1=winnerrankDF
x2=loserrankDF
X1_train, X1_test, y1_train, y1_test = train_test_split(x1, y1, test_size=0.33, random_state=42)
X2_train, X2_test, y2_train, y2_test = train_test_split(x2, y2, test_size=0.33, random_state=42)

In [67]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
def randomForest(est,dep,X_train,X_test, y_train,y_test):
    print("Random Forest")
    rdforest = RandomForestClassifier(n_estimators=est,max_depth=dep)
    rdforest.fit(X_train, y_train)
    rdpreds = rdforest.predict(X_test)
    print ("\tMean Squared Error: ",metrics.mean_squared_error(y_test,rdpreds))
    print ("\tR2 Score: ",metrics.r2_score(y_test,rdpreds))
    print ("\tTraining Accuracy: ",rdforest.score(X_train, y_train)*100)
    print ("\tTest Accuracy: ",metrics.accuracy_score(np.round(y_test),np.round(rdpreds))*100)
randomForest(100,70,X1_train,X1_test, y1_train,y1_test)
#randomForest(100,70,X2_train,X2_test, y2_train,y2_test)

Random Forest

c:\users\angad dhillon\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

	Mean Squared Error:  10667.013546798029
	R2 Score:  0.32592551493899113
	Training Accuracy:  100.0
	Test Accuracy:  45.689655172413794

from xgboost import XGBClassifier
def xgBoost(X_train,X_test, y_train,y_test):
    print("Xg Boost")
    xgboost1 = XGBClassifier()
    xgboost1.fit(X_train, y_train)
    xgpreds = xgboost1.predict(X_test)
    print ("\tMean Squared Error: ",metrics.mean_squared_error(y_test,xgpreds))
    print ("\tR2 Score: ",metrics.r2_score(y_test,xgpreds))
    print ("\tTraining Accuracy: ",xgboost1.score(X_train, y_train)*100)
    print ("\tTest Accuracy: ",metrics.accuracy_score(np.round(y_test),np.round(xgpreds))*100)
    return xgpreds
#xgBoost(X1_train,X1_test, y1_train,y1_test)
xgBoost(X2_train,X2_test, y2_train,y2_test)

In [68]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor

def randomForest(est,dep,X_train,X_test, y_train,y_test):
    print("Adaboost")
    rng = np.random.RandomState(1)
    rdforest = AdaBoostRegressor(DecisionTreeRegressor(max_depth=70),
                          n_estimators=100, random_state=rng)
    rdforest.fit(X_train, y_train)
    rdpreds = rdforest.predict(X_test)
    print ("\tMean Squared Error: ",metrics.mean_squared_error(y_test,rdpreds))
    print ("\tR2 Score: ",metrics.r2_score(y_test,rdpreds))
    print ("\tTraining Accuracy: ",rdforest.score(X_train, y_train)*100)
    print ("\tTest Accuracy: ",metrics.accuracy_score(np.round(y_test),np.round(rdpreds))*100)
#randomForest(100,70,X1_train,X1_test, y1_train,y1_test)
randomForest(100,70,X2_train,X2_test, y2_train,y2_test)

Adaboost

c:\users\angad dhillon\appdata\local\programs\python\python36\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

	Mean Squared Error:  104.67118226600985
	R2 Score:  0.996631446087142
	Training Accuracy:  99.99863411298794
	Test Accuracy:  14.408866995073891